# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_LAYERSCAPE) += arc-ucls1012a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += arc-ucls1012a-som120.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += arc-ucls1012a-som314s.dtb

dtb-$(CONFIG_ARCH_MXC) += ucimx93-som144.dtb
dtb-$(CONFIG_ARCH_MXC) += ucimx93-som144-tsdc11.dtb
dtb-$(CONFIG_ARCH_MXC) += ucimx93-som144-ucevo10.dtb
dtb-$(CONFIG_ARCH_MXC) += ucimx93-som144-ucevo20.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
