# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_LAYERSCAPE) += arc-ucls1012a.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += arc-ucls1012a-som314s.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
